### ISSUE TITLE
dependency build issue with color-thief

### ISSUE THREAD

**Issue by un1crom** [HeyMaslo/companionserver#13]
color thief module doesn't plan nice on new builds of node etc. so it has to be rebuilt to match the version the host OS has running.  sigh.

companionserver/apis/node_modules/color-thief/node_modules/canvas/build/Release/canvas.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 64. This version of Node.js requires
NODE_MODULE_VERSION 72. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1187:18)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/home/bigdatakane/code/companionserver/apis/node_modules/color-thief/node_modules/canvas/lib/bindings.js:3:18)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)

**Comment by un1crom** [comment]
this issue only is a problem if you take the code base and want to dev with it.  that is.  if your node version is higher than the node version used to build the npm bindings for "canvas" you will run into problems.  

- uninstall canvas in 'node_modules'... and in any other sub director it might exist
- npm install canvas... it will rebuild against the correct node module


this does not affect any containerized build as the container already has the node version / passing build in it.
