### ISSUE TITLE
Tensor is wrong shape or rather tensor model is having trouble with a tensortype

### ISSUE THREAD

**Issue by un1crom** [HeyMaslo/companionserver#14]
the image Segmentation/ deep lap model in build 1.0.4 doesn't like the tensor it's being given.

http://localhost:8080/tensorflowlocal/deeplab/deeplab_pascal_1_default_1/model.json?tfjs-format=file
Error: The dtype of dict['ImageTensor'] provided in model.execute(dict) must be int32, but was float32
    at Object.assert (/usr/src/app/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:546:15)
    at /usr/src/app/node_modules/@tensorflow/tfjs-converter/dist/tf-converter.node.js:5826:26
    at Array.forEach (<anonymous>)
    at GraphExecutor.checkInputShapeAndType (/usr/src/app/node_modules/@tensorflow/tfjs-converter/dist/tf-converter.node.js:5813:29)
    at GraphExecutor.execute (/usr/src/app/node_modules/@tensorflow/tfjs-converter/dist/tf-converter.node.js:5527:14)
    at GraphModel.execute (/usr/src/app/node_modules/@tensorflow/tfjs-converter/dist/tf-converter.node.js:6180:36)
    at /usr/src/app/node_modules/@tensorflow-models/deeplab/dist/index.js:99:43
    at /usr/src/app/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:3075:22
    at Engine.scopedRun (/usr/src/app/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:3085:23)
    at Engine.tidy (/usr/src/app/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:3074:21)

**Comment by un1crom** [comment]
important to include the right bundleddependencies... https://cloud.google.com/functions/docs/writing/specifying-dependencies-nodejs
